# https://taskfile.dev

version: '3'

tasks:
  fmt:
    cmds:
      - cargo +nightly fmt --all
      - cd examples/openai-proxy-js-example && npm run format

  check:
    cmds:
      - cargo +nightly check --workspace
